genres = [
    ("Action", "target.png"),
    ("Adventure", "steering-wheel.png"),
    ("Animation", "bear.png"),
    ("Fantasy", "magic-wand.png"),
    ("Sci-Fi", "ufo.png"),
    ("Documentary", "documentary.png"),
    ("History", "pillar.png"),
    ("Comedy", "masks.png"),
    ("Family", "sofa.png"),
]

crew_cast = [
    {
        "id": 1,
        "name": "Hailee Steinfeld",
        "roles": ["Actress"],
        "dob": "1996-12-11",
        "nationality": ["American"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 1,
        "watched": 12,
        "gender": "Female",
        "image": "hailee.jpg",
        "bio": "Hailee Steinfeld ( born December 11, 1996) is an American actress and singer. "
               "She had her breakthrough with the western film True Grit ( 2010), which earned her various accolades, "
               "including nominations for an Academy Award and a BAFTA Award.",
        "movies": [3, 2, 8, 4],
        "watchlists": [6],
    },
    {
        "id": 2,
        "name": "Emma Watson",
        "roles": ["Actress"],
        "nationality": ["British"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 2,
        "watched": 11,
        "dob": "1990-04-15",
        "gender": "Female",
        "image": "emma.jpeg",
        "bio": "Emma Charlotte Duerre Watson is an English actress. Known for her roles in both blockbusters "
               "and independent films, she has received a selection of accolades, including a Young Artist Award "
               "and three MTV Movie Awards.",
        "movies": [6, 5],
        "watchlists": [1],
    },
    {
        "id": 3,
        "name": "Michael Fassbender",
        "roles": ["Actor"],
        "nationality": ["German", "Irish"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 3,
        "watched": 10,
        "dob": "1977-04-02",
        "gender": "Male",
        "image": "fass.jpeg",
        "bio": "Michael Fassbender is a German-Irish actor. After studying at the Drama Centre London he became known "
               "for playing intense roles in film and television. He is the recipient of various accolades, "
               "including nominations for two Academy Awards, four BAFTA Awards and three Golden Globe Awards.",
        "movies": [11, 2, 7],
        "watchlists": [1, 2, 3, 4, 5, 6, 7],
    },
    {
        "id": 4,
        "name": "Christopher Nolan",
        "roles": ["Director", "Producer"],
        "nationality": ["British", "American"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 4,
        "watched": 8,
        "dob": "1970-07-30",
        "gender": "Male",
        "image": "nolan.jpg",
        "bio": "Sir Christopher Edward Nolan is a British and American filmmaker. Known for blockbusters with complex "
               "storytelling produced for Hollywood studios, he is considered a leading filmmaker of the 21st century. "
               "Nolan's films have earned over $6.6 billion worldwide, making him the seventh-highest-grossing "
               "film director. ",
        "movies": [1, 2, 3, 7, 8, 9, 12],
        "watchlists": [1, 2, 3, 4, 5, 6, 7],
    },
    {
        "id": 5,
        "name": "Brad Pitt",
        "roles": ["Producer", "Actor"],
        "nationality": ["American"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 5,
        "watched": 7,
        "dob": "1963-12-18",
        "gender": "Male",
        "image": "pitt.jpeg",
        "bio": "William Bradley Pitt is an American actor and film producer. He is the recipient of various accolades, "
               "including two Academy Awards, two British Academy Film Awards, two Golden Globe Awards, "
               "and a Primetime Emmy Award.",
        "movies": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "watchlists": [4, 5],
    },
    {
        "id": 6,
        "name": "Emily Blunt",
        "roles": ["Actress"],
        "nationality": ["British"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 6,
        "watched": 5,
        "dob": "1983-02-28",
        "gender": "Female",
        "image": "emily.jpeg",
        "bio": "Emily Olivia Laura Blunt is a British actress. She is the recipient of several accolades, "
               "including a Golden Globe Award and two Screen Actors Guild Awards, in addition to nominations "
               "for an Academy Award and four British Academy Film Awards. Forbes ranked her as one of the "
               "highest-paid actresses in the world in 2020.",
        "movies": [1, 2, 3, 9, 10, 11, 12],
        "watchlists": [4, 5],
    },
    {
        "id": 7,
        "name": "Dwayne Johnson",
        "roles": ["Actor", "Wrestler"],
        "nationality": ["American"],
        "rotten_tomatoes_rating": 99,
        "imdb_rating": 8.5,
        "ranking": 7,
        "watched": 10,
        "dob": "1972-05-02",
        "gender": "Male",
        "image": "rock.jpeg",
        "bio": "Dwayne Douglas Johnson (born May 2, 1972), also known by his ring name The Rock, is an American actor "
               "and professional wrestler. He is signed to WWE, where he performs on a part-time basis. Widely "
               "regarded as one of the greatest professional wrestlers of all time, Johnson was integral to the "
               "development and success of the World Wrestling Federation (WWF, now WWE) during the Attitude Era. "
               "He wrestled for the WWF full-time for eight years before pursuing an acting career. His films have "
               "grossed over $3.5 billion in North America and over $12.5 billion worldwide, making him one of the "
               "world's highest-grossing and highest-paid actors. He is a co-owner of the United Football League, "
               "a member of the board of directors of TKO Group Holdings—the parent company of UFC and WWE—and "
               "co-founder of Seven Bucks Productions.",
        "movies": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "watchlists": [1, 7],
    }
]

movies = [
    {
        "id": 1,
        "title": "The Silence of the Lambs",
        "directors": ["Jonathan Demme"],
        "imdb_rating": 8.6,
        "rotten_tomatoes_rating": 96,
        "ranking": 1,
        "year": 1991,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "The Silence of the Lambs",
        "franchise_id": 1,
        "runtime": "1hrs 58mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Adventure", "Fantasy", "Action"],
        "watched": 2,
        "album_ids": [1, 3, 4, 7],
        "description": "Jodie Foster stars as Clarice Starling, a top student at the FBI's training academy. "
                       "Jack Crawford (Scott Glenn) wants Clarice...",
        "poster_main": "silence.jpg",
        "poster_stack": ["cloudy.jpg", "strange2.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 2,
        "title": "Cloudy with a Chance of Meatballs",
        "directors": ["Phil Lord", "Chris Miller"],
        "imdb_rating": 7.0,
        "rotten_tomatoes_rating": 86,
        "ranking": 2,
        "year": 2009,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Cloudy with a Chance of Meatballs",
        "franchise_id": 2,
        "runtime": "1hrs 30mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Animation", "Family", "Comedy"],
        "watched": 6,
        "album_ids": [1, 3, 4, 7],
        "description": "When hard times hit Swallow Falls, its townspeople can only afford to eat sardines. "
                       "Flint Lockwood, a failed inventor, thinks he has the answer to the town's crisis...",
        "poster_main": "cloudy.jpg",
        "poster_stack": ["strange2.jpg", "silence.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 3,
        "title": "Doctor Strange in the Multiverse of Madness",
        "directors": ["Sam Raimi"],
        "imdb_rating": 7.4,
        "rotten_tomatoes_rating": 74,
        "ranking": 3,
        "year": 2022,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Doctor Strange",
        "franchise_id": 3,
        "runtime": "2hrs 6mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Comedy", "Horror", "Adventure"],
        "watched": 5.7,
        "album_ids": [5, 7],
        "description": "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel "
                       "across multiverses, to battle multiple threats...",
        "poster_main": "strange2.jpg",
        "poster_stack": ["silence.jpg", "cloudy.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 4,
        "title": "Avengers: Endgame",
        "directors": ["Anthony Russo", "Joe Russo"],
        "imdb_rating": 8.4,
        "rotten_tomatoes_rating": 94,
        "ranking": 4,
        "year": 2019,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Avengers",
        "franchise_id": 4,
        "runtime": "3hrs 1mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 15,
        "album_ids": [1, 3, 4, 7],
        "description": "After the devastating events of Infinity War, the universe is in ruins. "
                       "With the help of remaining allies, the Avengers assemble once more in order to reverse "
                       "Thanos' actions and restore balance to the universe.",
        "poster_main": "endgame.jpeg",
        "poster_stack": ["avengers.jpg", "angry2.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 5,
        "title": "Black Panther",
        "directors": ["Ryan Coogler"],
        "imdb_rating": 7.3,
        "rotten_tomatoes_rating": 96,
        "ranking": 5,
        "year": 2018,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Black Panther",
        "franchise_id": 5,
        "runtime": "2hrs 14mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 12.6,
        "album_ids": [1, 3, 4, 7],
        "description": "T'Challa, the King of Wakanda, must defend his nation from an old foe in a battle for the throne.",
        "poster_main": "panther.jpeg",
        "poster_stack": ["interstellar.jpg", "ralph"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
        ],
    },
    {
        "id": 6,
        "title": "Captain Marvel",
        "directors": ["Anna Boden", "Ryan Fleck"],
        "imdb_rating": 6.8,
        "rotten_tomatoes_rating": 79,
        "ranking": 6,
        "year": 2019,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Captain Marvel",
        "franchise_id": 6,
        "runtime": "2hrs 3mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 20.5,
        "album_ids": [5],
        "description": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
        "poster_main": "marvel.jpeg",
        "poster_stack": ["moana2.jpg", "ultron.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
        ],
    },
    {
        "id": 7,
        "title": "Spider-Man: Far From Home",
        "directors": ["Jon Watts"],
        "imdb_rating": 7.5,
        "rotten_tomatoes_rating": 90,
        "ranking": 7,
        "year": 2019,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Spider-Man",
        "franchise_id": 7,
        "runtime": "2hrs 9mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 25.5,
        "album_ids": [1, 3, 4, 7],
        "description": "Following the events of Avengers: Endgame, Peter Parker must step up to take on new threats in a world that has changed forever.",
        "poster_main": "spiderman_far.jpeg",
        "poster_stack": ["avengers.jpg", "endgame.jpeg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
        ],
    },
    {
        "id": 8,
        "title": "Angry Birds 2",
        "directors": ["Thurop Van Orman"],
        "imdb_rating": 6.4,
        "rotten_tomatoes_rating": 76,
        "ranking": 8,
        "year": 2019,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Angry Birds",
        "franchise_id": 8,
        "runtime": "1hrs 37mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Animation", "Adventure", "Comedy"],
        "watched": 30.5,
        "album_ids": [1, 3, 4, 7],
        "description": "The flightless angry birds and the scheming green pigs take their beef to the next level.",
        "poster_main": "angry2.jpg",
        "poster_stack": ["dogs.jpg", "moana2.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 9,
        "title": "Isle of Dogs",
        "directors": ["Wes Anderson"],
        "imdb_rating": 7.8,
        "rotten_tomatoes_rating": 90,
        "ranking": 9,
        "year": 2018,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "",
        "franchise_id": "",
        "runtime": "1hrs 41mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Animation", "Adventure", "Comedy"],
        "watched": 35.5,
        "album_ids": [1, 3, 4, 7],
        "description": "Set in Japan, Isle of Dogs follows a future dystopian world where dogs have been exiled to Trash Island due to a canine flu outbreak.",
        "poster_main": "dogs.jpg",
        "poster_stack": ["angry2.jpg", "moana2.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 10,
        "title": "Inception",
        "directors": ["Christopher Nolan"],
        "imdb_rating": 8.8,
        "rotten_tomatoes_rating": 86,
        "ranking": 10,
        "year": 2010,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "",
        "franchise_id": "",
        "runtime": "2hrs 28mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 9.5,
        "album_ids": [5],
        "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        "poster_main": "inception.jpg",
        "poster_stack": ["interstellar.jpg", "dogs.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 11,
        "title": "Interstellar",
        "directors": ["Christopher Nolan"],
        "imdb_rating": 8.6,
        "rotten_tomatoes_rating": 72,
        "ranking": 11,
        "year": 2014,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "",
        "franchise_id": "",
        "runtime": "2hrs 49mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Adventure", "Drama", "Sci-Fi"],
        "watched": 8.5,
        "album_ids": [5],
        "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "poster_main": "interstellar.jpg",
        "poster_stack": ["inception.jpg", "dogs.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 12,
        "title": "Avengers: Age of Ultron",
        "directors": ["Joss Whedon"],
        "imdb_rating": 7.3,
        "rotten_tomatoes_rating": 75,
        "ranking": 12,
        "year": 2015,
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "franchise": "Avengers",
        "franchise_id": 4,
        "runtime": "2hrs 21mins",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 5.5,
        "album_ids": [2],
        "description": "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and it is up to the Avengers to stop the villainous Ultron from enacting his terrible plans.",
        "poster_main": "ultron.jpg",
        "poster_stack": ["avengers.jpg", "endgame.jpeg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
]

watchlists = [
    {
        "id": 1,
        "title": "All Island Animations",
        "directors": ["Phil Lord, Chris Miller"],
        "imdb_rating": 7.0,
        "rotten_tomatoes_rating": 86,
        "type": "Marathon",
        "created": "2023-10-01",
        "era": "2023 - ",
        "genres": ["Animation", "Family", "Comedy"],
        "description": "All Island Animations is a collection of animated films that take place on various islands. "
                       "From tropical paradises to frozen tundras, these films explore the adventures of characters "
                       "living in unique island settings.",
        "posters": ["angry2.jpg", "dogs.jpg", "moana2.jpg"],
        "total_runtime": "12hrs 30mins",
        "film_ids": [8, 9],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "watched": 10,
        "film_count": 16,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 2,
        "title": "All Marvel Movies",
        "directors": ["Guy Richie", "Michael Bay"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "type": "Studio",
        "created": "2023-10-01",
        "era": "2023 - ",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "description": "All Marvel Movies is a collection of films from the Marvel Cinematic Universe. These films feature superheroes, epic battles, and interconnected storylines that span across the universe.",
        "posters": ["avengers.jpg", "endgame.jpeg", "panther.jpeg", "marvel.jpeg"],
        "total_runtime": "21hrs 16mins",
        "film_ids": [1, 2, 3, 4, 5],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "watched": 100,
        "film_count": 20,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 3,
        "title": " All Sci-Fi Animations",
        "directors": ["Rich Moore", "Phil Johnston", "Byron Howard"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "type": "Marathon",
        "created": "2023-10-01",
        "era": "2023 - ",
        "genres": ["Animation", "Adventure", "Sci-Fi"],
        "description": "All Sci-Fi Animations is a collection of animated films that explore futuristic themes, "
                       "advanced technology, and imaginative worlds. These films take viewers on thrilling adventures "
                       "through space and time.",
        "posters": ["ralph.jpg", "zoo.jpg"],
        "total_runtime": "7hrs 12mins",
        "film_ids": [6, 7],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "watched": 10,
        "film_count": 29,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 4,
        "title": "All Fantasy Animations",
        "directors": ["Rich Moore", "Phil Johnston", "Byron Howard"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "type": "Marathon",
        "created": "2023-10-01",
        "era": "2023 - ",
        "genres": ["Animation", "Adventure", "Fantasy"],
        "description": "All Fantasy Animations is a collection of animated films that transport viewers to magical worlds, "
                       "where anything is possible. These films feature fantastical creatures, epic quests, and enchanting stories.",
        "posters": ["cloudy.jpg", "luck.jpg"],
        "total_runtime": "10hrs 12mins",
        "film_ids": [8, 9],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 300000000,
        "watched": 15,
        "film_count": 20,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 5,
        "title": "Favorite Movies",
        "directors": ["Christopher Nolan", "Rich Moore"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "type": "Marathon",
        "created": "2023-10-01",
        "era": "2023 - ",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "description": "Favorite Movies is a collection of films that have left a lasting impact on audiences. "
                       "These films are known for their exceptional storytelling, memorable characters, and cinematic excellence.",
        "posters": ["inception.jpg", "interstellar.jpg", "ultron.jpg"],
        "total_runtime": "24hrs 12mins",
        "film_ids": [10, 11, 12],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 30000000000,
        "watched": 20,
        "film_count": 15,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 6,
        "title": "The Expanse",
        "directors": ["Mark Fergus", "Hawk Ostby"],
        "imdb_rating": 8.5,
        "rotten_tomatoes_rating": 95,
        "type": "TV Show",
        "created": "2015-10-01",
        "era": "2015 - 2023",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "description": "The Expanse is a science fiction television series set in a future where humanity has colonized the solar system. "
                       "It follows a disparate band of antiheroes who unwittingly unravel and place themselves at the center of a conspiracy that threatens peace across the system.",
        "posters": ["expanse1.jpg", "expanse2.jpg", "expanse3.jpg", "expanse4.jpg"],
        "total_runtime": "53hrs 12mins",
        "film_ids": [5, 7, 1],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 3000000000,
        "watched": 10,
        "film_count": 20,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 7,
        "title": "Cool Drama Movies of the Past",
        "directors": ["Christopher Nolan", "Rich Moore"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "type": "Marathon",
        "created": "2023-10-01",
        "era": "1991 - 2022",
        "genres": ["Drama", "Action", "Adventure"],
        "description": "Cool Drama Movies is a collection of films that explore complex characters and emotional narratives. "
                       "These films are known for their powerful performances and thought-provoking themes.",
        "posters": ["silence.jpg", "luck.jpg", "ralph.jpg"],
        "total_runtime": "12hrs 12mins",
        "film_ids": [8, 9, 10],
        "released": "12th January, 2012",
        "writers": ["Charles Dickens", "Edgar Allan Poe", "Ian Fleming"],
        "languages": ["English", "Swahili", "Xhosa"],
        "countries": ["UK", "USA", "Kenya"],
        "boxoffice": 3000000000,
        "watched": 20,
        "film_count": 15,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
]
