genres = [
        ("Action", "target.png"),
        ("Adventure", "steering-wheel.png"),
        ("Animation", "bear.png"),
        ("Fantasy", "magic-wand.png"),
        ("Sci-Fi", "ufo.png"),
        ("Documentary", "documentary.png"),
        ("History", "pillar.png"),
        ("Comedy", "masks.png"),
        ("Family", "sofa.png"),
      ]

movies = [
    {
        "id": 1,
        "title": "The Silence of the Lambs",
        "directors": ["Jonathan Demme"],
        "imdb_rating": 8.6,
        "rotten_tomatoes_rating": 96,
        "ranking": 1,
        "year": 1991,
        "runtime": "1hr 58min",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Adventure", "Fantasy", "Action"],
        "watched": 2,
        "description": "Jodie Foster stars as Clarice Starling, a top student at the FBI's training academy. "
                       "Jack Crawford (Scott Glenn) wants Clarice...",
        "poster_main": "silence.jpg",
        "poster_stack": ["cloudy.jpg", "strange2.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 2,
        "title": "Cloudy with a Chance of Meatballs",
        "directors": ["Phil Lord, Chris Miller"],
        "imdb_rating": 7.0,
        "rotten_tomatoes_rating": 86,
        "ranking": 2,
        "year": 2009,
        "runtime": "1hr 30min",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Animation", "Family", "Comedy"],
        "watched": 6,
        "description": "When hard times hit Swallow Falls, its townspeople can only afford to eat sardines. "
                       "Flint Lockwood, a failed inventor, thinks he has the answer to the town's crisis...",
        "poster_main": "cloudy.jpg",
        "poster_stack": ["strange2.jpg", "silence.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
  {
        "id": 3,
        "title": "Doctor Strange in the Multiverse of Madness",
        "directors": ["Sam Raimi"],
        "imdb_rating": 7.4,
        "rotten_tomatoes_rating": 74,
        "ranking": 3,
        "year": 2022,
        "runtime": "2hr 6min",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Comedy", "Horror", "Adventure"],
        "watched": 5.7,
        "description": "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel "
                       "across multiverses, to battle multiple threats...",
        "poster_main": "strange2.jpg",
        "poster_stack": ["silence.jpg", "cloudy.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
  },
  {
        "id": 4,
        "title": "Avengers: Endgame",
        "directors": ["Anthony Russo", "Joe Russo"],
        "imdb_rating": 8.4,
        "rotten_tomatoes_rating": 94,
        "ranking": 4,
        "year": 2019,
        "runtime": "3hr 1min",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 15,
        "description": "After the devastating events of Infinity War, the universe is in ruins. "
                        "With the help of remaining allies, the Avengers assemble once more in order to reverse "
                        "Thanos' actions and restore balance to the universe.",
        "poster_main": "endgame.jpeg",
        "poster_stack": ["avengers.jpg", "angry2.jpg"],
        "cast": [
                {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
                {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
                {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
                {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
                {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
      ],
  },
  {
        "id": 5,
        "title": "Black Panther",
        "directors": ["Ryan Coogler"],
        "imdb_rating": 7.3,
        "rotten_tomatoes_rating": 96,
        "ranking": 5,
        "year": 2018,
        "runtime": "2hr 14min",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 12.6,
        "description": "T'Challa, the King of Wakanda, must defend his nation from an old foe in a battle for the throne.",
        "poster_main": "panther.jpeg",
        "poster_stack": ["interstellar.jpg", "ralph"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
        ],
  },
  {
        "id": 6,
      "title": "Captain Marvel",
      "directors": ["Anna Boden", "Ryan Fleck"],
        "imdb_rating": 6.8,
        "rotten_tomatoes_rating": 79,
        "ranking": 6,
        "year": 2019,
        "runtime": "2hr 3min",
        "trailer": "https://www.youtube.com/watch?v=ZWY2j0g1v4E",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "watched": 20.5,
        "description": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
        "poster_main": "marvel.jpeg",
        "poster_stack": ["moana2.jpg", "ultron.jpg"],
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
        ],
    },
]



watchlists = [
    {
        "id": 1,
        "title": "All Island Animations",
        "directors": ["Phil Lord, Chris Miller"],
        "imdb_rating": 7.0,
        "rotten_tomatoes_rating": 86,
        "created": "2023-10-01",
        "genres": ["Animation", "Family", "Comedy"],
        "description": "All Island Animations is a collection of animated films that take place on various islands. "
                       "From tropical paradises to frozen tundras, these films explore the adventures of characters "
                       "living in unique island settings.",
        "posters": ["angry2.jpg", "dogs.jpg", "moana2.jpg"],
        "watched": 10,
        "film_count": 16,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 2,
        "title": "All Marvel Movies",
        "directors": ["Various"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "created": "2023-10-01",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "description": "All Marvel Movies is a collection of films from the Marvel Cinematic Universe. These films feature superheroes, epic battles, and interconnected storylines that span across the universe.",   
        "posters": ["avengers.jpg", "endgame.jpeg", "panther.jpeg", "marvel.jpeg"],
        "watched": 100,
        "film_count": 20,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 3,
        "title": " All Sci-Fi Animations",
        "directors": ["Rich Moore", "Phil Johnston", "Byron Howard"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "created": "2023-10-01",
        "genres": ["Animation", "Adventure", "Sci-Fi"],
        "description": "All Sci-Fi Animations is a collection of animated films that explore futuristic themes, "
                       "advanced technology, and imaginative worlds. These films take viewers on thrilling adventures "
                       "through space and time.",
        "posters": ["ralph.jpg", "zoo.jpg"],
        "watched": 10,
        "film_count": 29,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
    {
        "id": 4,
        "title": "All Fanasy Animations",
        "directors": ["Rich Moore", "Phil Johnston", "Byron Howard"],
        "imdb_rating": 8.0,
        "rotten_tomatoes_rating": 85,
        "created": "2023-10-01",
        "genres": ["Animation", "Adventure", "Fantasy"],
        "description": "All Fantasy Animations is a collection of animated films that transport viewers to magical worlds, "
                       "where anything is possible. These films feature fantastical creatures, epic quests, and enchanting stories.",
        "posters": ["cloudy.jpg", "luck.jpg"],
        "watched": 15,
        "film_count": 20,
        "cast": [
            {"name": "CHRISTOPHER NOLAN", "role": "Director", "image": "nolan.jpg"},
            {"name": "BRAD PITT", "role": "John Carter", "image": "pitt.jpeg"},
            {"name": "EMILY BLUNT", "role": "Sarah Frost", "image": "emily.jpeg"},
            {"name": "EMMA STONE", "role": "Lucy Blake", "image": "emma.jpeg"},
            {"name": "DWAYNE JOHNSON", "role": "Max Thunder", "image": "rock.jpeg"},
        ],
    },
]